### ISSUE TITLE
[bug]Debian上，备份好的文件会被当成老旧的备份文件删掉

### ISSUE THREAD

**Issue by 2ndMessiah** [kshipeng/autoBackup#3]
首先祝作者龙年大吉！
我是从nodeseek来的，看见了您写的这个脚本，很对我的想法。跑了一下试了试，发现一个问题，备份好的文件会被当成老旧的备份文件删掉。

因为我不太会写shell script，就加了几个echo看了看变量，发现那个“timestamp”变量返回值是空的。
以下是我加了echo后的delete函数：
<img width="845" alt="image" src="https://github.com/kshipeng/autoBackup/assets/22229188/44ef4abc-2371-41ca-bc9f-7fcb8e1696d2">

执行结果是这样的：
<img width="630" alt="image" src="https://github.com/kshipeng/autoBackup/assets/22229188/9bd65d5a-d2c4-48ba-8812-fcea2794ac22">

ps 在一个Debian10、两台Debian11上面失败，两台Ubuntu20成功

请作者帮忙看看是那里可能有问题。谢谢！

**Comment by hbsgithub** [comment]
我在debian12上遇到了相同的问题，请问你是怎么解决的呢？

**Comment by hbsgithub** [comment]
我将
```shell 
local timestamp=$(echo "$file" | awk 'match($0, /[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}:[0-9]{2}:[0-9]{2}/) {print substr($0, RSTART, RLENGTH)}' | tr '_' ' ')
```
修改为
```shell 
local timestamp=$(echo "$file" | sed -n 's/.*\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\).*/\1/p' | tr '_' ' ')
```
解决了这一问题
